[package]
name = "fourier-fit"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", default-features = true, features = ["canvas"] }
ndarray = "0.17.1"
ndarray-linalg = "0.18.0"
num-complex = "0.4.6"
rustfft = "6.4.1"
scirs2 = "0.1.0-rc.2"
scirs2-signal = "0.1.0-rc.2"
