name: build-test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - runs_on: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - runs_on: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu

          # Windows x64
          - runs_on: windows-latest
            target: x86_64-pc-windows-msvc

          # Future support for Windows ARM64
          # - runs_on: windows-11-arm
          #   target: aarch64-pc-windows-msvc

          # macOS (arm64)
          - runs_on: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          # Build
          cargo build --locked --release --target ${{ matrix.target }}
