name: build-test

on:
  pull_request:
    branches:
        - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux (supported distros)
          - runs_on: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - runs_on: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu

          # Windows
          - runs_on: windows-latest
            target: x86_64-pc-windows-msvc
          - runs_on: windows-11-arm
            target: aarch64-pc-windows-msvc

          # NOTE: macos-14 is arm64-only; pick an intel label that exists for x86_64.
          - runs_on: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2

      - run: cargo build --locked --release --target ${{ matrix.target }}
