name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # required to create/upload release assets

env:
  BIN_NAME: ffit

jobs:
  build:
    name: build (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - runs_on: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            ext: ""
          - runs_on: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            ext: ""

          # Windows
          - runs_on: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

          # Furture support for Windows on arm
          # - runs_on: windows-11-arm
          #   target: aarch64-pc-windows-msvc
          #   ext: ".exe"

          # macOS (arm64)
          - runs_on: macos-latest
            target: aarch64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.runs_on }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/rust-build
        with:
          target: ${{ matrix.target }}
          bin_name: ${{ env.BIN_NAME }}
          ext: ${{ matrix.ext }}
          release: "true"
          package: "true"
          upload_artifact: "true"
          artifact_name: ${{ env.BIN_NAME }}-${{ matrix.target }}

  release:
    name: Upload artifacts to draft release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload assets to draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/**/*.tar.gz
            dist/**/*.zip
